version: '2.0' # optional since v1.27.0
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp
    ports:
      - "80:5000"
    restart: always
    networks: 
     - webnet
     
networks:
  webnet: